CatsArayuz/CatsArayuz/Controllers/GuvenlikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using CatsArayuz.Models;

namespace BilgiListeleme.Controllers
{
    public class GuvenlikController : Controller
    {
        DBCatsEntities db = new DBCatsEntities();
        // GET: Guvenlik
        [HttpGet]
        public ActionResult GirisYap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GirisYap(TBLAdminData t)
        { 
            var bilgiler = db.TBLAdminData.FirstOrDefault(x => x.UserName == t.UserName && x.Password == t.Password);
            if (bilgiler != null)
            {
                if (bilgiler.RolId == 1)
                {
                    FormsAuthentication.SetAuthCookie(bilgiler.UserName,false);
                    return RedirectToAction("AdminIndex", "AdminHome");
                }
                else if (bilgiler.RolId == 2)
                {
                    FormsAuthentication.SetAuthCookie(bilgiler.UserName, false);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return View("GirisYap1");
                }
            }
            else
            {
                return View("GirisYap1");
            }

        }
        public ActionResult SifremiUnuttum()
        {
            return View();
        }
        [HttpGet]
        public ActionResult GirisYap1()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GirisYap1(TBLAdminData t)
        {
            var bilgiler = db.TBLAdminData.FirstOrDefault(x => x.UserName == t.UserName && x.Password == t.Password);
            if (bilgiler.RolId == 1)
            {
                FormsAuthentication.SetAuthCookie(bilgiler.UserName, false);
                return RedirectToAction("AdminIndex", "AdminHome");
            }
            else if (bilgiler.RolId == 2)
            {
                FormsAuthentication.SetAuthCookie(bilgiler.UserName, false);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View("GirisYap1");
            }
        }
    }
}

CatsArayuz/CatsArayuz/Views/Guvenlik/GirisYap.cshtml
@model CatsArayuz.Models.TBLAdminData
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <title>Giriş Ekranı</title>

    <!-- Meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Google fonts -->
    <link href="//fonts.googleapis.com/css2?family=Kumbh+Sans:wght@300;400;700&display=swap" rel="stylesheet">

    <!-- CSS Stylesheet -->
    <link rel="stylesheet" href="~/starter/css/style.css" type="text/css" media="all" />

</head>

<body>
    <div class="signinform">
        <!-- container -->
        <div class="container">
            <!-- main content -->
            <div class="w3l-form-info">
                <div class="w3_info">
                    <h2>Giriş Yap</h2>
                    @using (Html.BeginForm("GirisYap", "Guvenlik", FormMethod.Post))
                    {
                        <div class="input-group">
                            <span><i class="fas fa-user" aria-hidden="true"></i></span>
                            <input type="text" placeholder="Kullanıcı Adını Giriniz" required="" name="UserName">
                        </div>
                        <div class="input-group">
                            <span><i class="fas fa-key" aria-hidden="true"></i></span>
                            <input type="Password" placeholder="Şifre" required="" name="Password">
                        </div>
                        <div class="form-row bottom">
                            <div class="form-check">
                                <input type="checkbox" id="remenber" name="remenber" value="remenber">
                                <label for="remenber"> Beni Hatırla?</label>
                            </div>
                            <a href="/Guvenlik/SifremiUnuttum/" class="forgot">Şifremi Unuttum?</a>
                        </div>
                        <button class="btn btn-primary btn-block" type="submit">Giriş Yap</button>

                    }
                    @*<p class="continue"><span>or Login with</span></p>
                        <div class="social-login">
                            <a href="#facebook">
                                <div class="facebook">
                                    <span class="fab fa-facebook-f" aria-hidden="true"></span>

                                </div>
                            </a>
                            <a href="#twitter">
                                <div class="twitter">
                                    <span class="fab fa-twitter" aria-hidden="true"></span>
                                </div>
                            </a>
                            <a href="#google">
                                <div class="google">
                                    <span class="fab fa-google" aria-hidden="true"></span>
                                </div>
                            </a>
                        </div>
                        <p class="account">Don't have an account? <a href="#signup">Sign up</a></p>*@
                </div>
            </div>
            <!-- //main content -->
        </div>
        <!-- //container -->
        <!-- footer -->
        <div class="footer">
            <p>
                &copy;Copyright 2022 <a href="https://www.catsbilisim.net/" target="blank">Cats</a> Bilişim Hizmetleri A.Ş Tüm Hakları Saklıdır
            </p>
        </div>
        <!-- footer -->
    </div>

    <!-- fontawesome v5-->
    <script src="js/fontawesome.js"></script>

</body>

</html>

CatsArayuz/CatsArayuz/Views/Guvenlik/GirisYap1.cshtml
@model CatsArayuz.Models.TBLAdminData
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <title>Giriş Ekranı</title>

    <!-- Meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Google fonts -->
    <link href="//fonts.googleapis.com/css2?family=Kumbh+Sans:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <!-- CSS Stylesheet -->

    <link rel="stylesheet" href="~/starter/css/style.css" type="text/css" media="all" />

</head>

<body>
    <div class="signinform">
        <!-- container -->
        <div class="container">
            <!-- main content -->
            <div class="w3l-form-info">
                <div class="w3_info">
                    <h2>Giriş Yap</h2>
                    @using (Html.BeginForm("GirisYap", "Guvenlik", FormMethod.Post))
                    {
                        <div class="input-group">
                            <span><i class="fas fa-user" aria-hidden="true"></i></span>
                            <input type="text" placeholder="Kullanıcı Adını Giriniz" required="" name="UserName">
                        </div>
                        <div class="input-group">
                            <span><i class="fas fa-key" aria-hidden="true"></i></span>
                            <input type="Password" placeholder="Şifre" required="" name="Password">
                        </div>
                        <div class="form-row bottom">
                            <div class="form-check">
                                <input type="checkbox" id="remenber" name="remenber" value="remenber">
                                <label for="remenber"> Beni Hatırla?</label>
                            </div>

                            <a href="/Guvenlik/SifremiUnuttum/" class="forgot">Şifremi Unuttum?</a>
                        </div>
                        <div class="w3-panel w3-red">
                            <p>Girdiğiniz Kullanıcı Adı yada Şifre yanlış.</p>
                        </div>
                        <button class="btn btn-primary btn-block" type="submit">Giriş Yap</button>

                    }

                </div>
            </div>
            <!-- //main content -->
        </div>
        <!-- //container -->
        <!-- footer -->
        <div class="footer">
            <p>
                &copy;Copyright 2022 <a href="https://www.catsbilisim.net/" target="blank">Cats</a> Bilişim Hizmetleri A.Ş Tüm Hakları Saklıdır
            </p>
        </div>
        <!-- footer -->
    </div>

    <!-- fontawesome v5-->
    <script src="js/fontawesome.js"></script>


</body>

</html>

CatsArayuz/CatsArayuz/Views/Guvenlik/SifremiUnuttum.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SifremiUnuttum</title>
</head>
<body>
    <div> 
        Bu konuda yapabileceğim birşey yok
    </div>

</body>
</html>