CatsArayuz/CatsArayuz/Controllers/GuncelleController.cs
using CatsArayuz.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using CatsArayuz;

namespace BilgiListeleme.Controllers
{
    public class GuncelleController : Controller
    {
        DBCatsEntities db = new DBCatsEntities();
        [Authorize(Roles = "Employee")]
        public ActionResult Index(int Id)
        {
            var hks = db.TBLVdsListe.Find(Id);
            return View(hks);
        }
        public ActionResult VeriGuncelle(TBLVdsListe c)
        {
            var vgn = db.TBLVdsListe.Find(c.Id);
            vgn.SirketAdı = c.SirketAdı;
            vgn.VdsKullanıcıAdı = c.VdsKullanıcıAdı;
            vgn.VdsIp = c.VdsIp;
            vgn.VdsPw = c.VdsPw;
            vgn.TeamViewer = c.TeamViewer;
            vgn.TeamViewerPw = c.TeamViewerPw;
            vgn.AnyDesk = c.AnyDesk;
            vgn.AnydeskPw = c.AnydeskPw;
            vgn.Notes = c.Notes;
            db.SaveChanges();
            return View("Index");
        }
        public ActionResult VeriSil(int Id)
        {
            var dlt = db.TBLVdsListe.Find(Id);
            db.TBLVdsListe.Remove(dlt);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

CatsArayuz/CatsArayuz/Views/Guncelle/Index.cshtml
@using CatsArayuz.Models
@model CatsArayuz.Models.TBLVdsListe
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("VeriGuncelle", "Guncelle", FormMethod.Post))
{
    <table>
        <tr>
            <td>
                <div class="container" style="width:350px;">
                    <div class="panel panel-default" style="width: 300px;">
                        <div class="panel-body">
                            <label>Şirket Adı</label>
                            @Html.TextBoxFor(y => y.SirketAdı, new { @class = "form-control" })

                            <label>Vds Kullanıcı Adı</label>
                            @Html.TextBoxFor(y => y.VdsKullanıcıAdı, new { @class = "form-control" })

                            <label>Vds Ip</label>
                            @Html.TextBoxFor(y => y.VdsIp, new { @class = "form-control" })

                            <label>Vds Şifresi</label>
                            @Html.TextBoxFor(y => y.VdsPw, new { @class = "form-control" })
                            <br />
                            <br />@Html.HiddenFor(y => y.Id, new { @class = "form-control" })
                            <br />
                            <br />
                            <br />

                        </div>
                    </div>
                </div>
            </td>
            <td>
                <div class="container" style="width:350px;">
                    <div class="panel panel-default" style="width:300px;">
                        <div class="panel-body">
                            <label>TeamViewer </label>
                            @Html.TextBoxFor(y => y.TeamViewer, new { @class = "form-control" })
                            <label>TeamViewer Şifresi</label>
                            @Html.TextBoxFor(y => y.TeamViewerPw, new { @class = "form-control" })
                            <label>AnyDesk Id</label>
                            @Html.TextBoxFor(y => y.AnyDesk, new { @class = "form-control" })

                            <label>AnyDesk Şifresi</label>
                            @Html.TextBoxFor(y => y.AnydeskPw, new { @class = "form-control" })
                            <label>SplashTop</label>
                            @Html.TextBoxFor(y => y.SplashTop, new { @class = "form-control" })
                            <label>SplashTop Şifresi</label>
                            @Html.TextBoxFor(y => y.SplashTopPw, new { @class = "form-control" })

                        </div>
                    </div>
                </div>
            </td>
            <td>
                <div class="container" style="width:350px;">
                    <div class="panel panel-default" style="width:300px;">
                        <div class="panel-body">
                            <br />
                            <br />
                            <label>Notlar</label>
                            @Html.TextAreaFor(y => y.Notes, new { @class = "form-control" })


                            <br />
                            <br />
                            <br />
                        </div>
                    </div>
                </div>
                <button class="btn btn-info" style="margin-left:200px;">Güncelle</button>


            </td>
        </tr>
    </table>
}